### PR TITLE
Issue #21: Terminating find_pid expression with '/'

### LINKED ISSUE #21: find_pid within init.d script can qualify different Tomcat installations
When a consumer installs multiple instances of Tomcat on a host, it cause a scenario where the `find_pid` bash function, can actually qualify a wrong instance (based on the naming applied by the consumer). Example:
- my_app
- my_app_1

With these two, there could be the following installations (and running PIDs):
- /opt/tomcat/my_app (pid: 123)
- /opt/tomcat/my_app_2 (pid: 456)

While both of these service processes are running, you could issue `service tomcat_my_app status`, but it actually qualifies PID 456 (rather than PID 123). This because the `find_pid` function is not terminating on the `$CATALINA_HOME` with a slash, and follows it with a `.*`.

``` bash
find_pid() {
  PID=`pgrep -u $USER -f "$CATALINA_HOME.*$START_CLASS"`
}
```

Where `$CATALINA_HOME` can be `/opt/tomcat/my_app` in the script, which allows it to qualify `/opt/tomcat/my_app_1` when executing pgrep. One proposed way of fixing this, is terminating the `$CATALINA_HOME` with `/`.

### PR DESCRIPTION
**Pull request by cchesser**
Applying the fix to terminate the expression used to qualify service processes PIDs.

Fixes: #21 

Test kitchen verify results are [here](https://gist.github.com/cchesser/df0214c29b89e2721d00cc4623a94e63).

### CODE REVIEW

**Comment by cchesser** [comment]
Note, played around with service functions to ensure it qualifies the pid on the test where `my_tomcat` and `my_tomcat_2` both exist, to ensure when issuing commands against `my_tomcat` service, it doesn't also qualify `my_tomcat_2` case. 

Setup:
- Verify that if both service processes are running
- You stop `my_tomcat`
- Then do a status check to see if `my_tomcat` is still running, it _doesn't qualify_ `my_tomcat_2` (previously could qualify `my_tomcat_2`)

``` bash
> sudo service tomcat_my_tomcat stop
Shutting down my_tomcat:
Attempting to shutdown my_tomcat...
su: warning: cannot change directory to /home/my_user: No such file or directory
Using CATALINA_BASE:   /opt/my_dir/my_tomcat
Using CATALINA_HOME:   /opt/my_dir/my_tomcat
Using CATALINA_TMPDIR: /opt/my_dir/my_tomcat/temp
Using JRE_HOME:        /usr/lib/jvm/java-1.8.0
Using CLASSPATH:       /opt/my_dir/my_tomcat/bin/bootstrap.jar:/opt/my_dir/my_tomcat/bin/tomcat-juli.jar
my_tomcat has stopped
> sudo service tomcat_my_tomcat status
my_tomcat is stopped
```

:bulb: _I noted on the other issue (#15) for the 'No such file or directory' problem, as this looks to have been recently changed in the integration tests (which can be corrected on this PR if that is preferred)._

**Comment by EdwardSkoviak** [comment]
Does the 'No such file or directory' problem impact the tests at all? It looks like its just a warning and we are still able to stop/start the service fine. Either way, feel free to fix the vm so a home directory exists for the service user.

**Comment by EdwardSkoviak** [comment]
Went ahead and compared the two different pgrep commands for the 'my_tomcat' service on the test VM. The old one pulled down PIDs for both services (so the last one printed to stdout is returned), the new command resolves only one PID since '/opt/my_dir/my_tomcat/${dependency}' is present in the process command.

If we wanted to exclude the (unrealistic) possibility of still resolving two PIDs when nesting a service within a service, we could do something like this instead (take note of the space and looking for catalina.home):

```
pgrep -u $USER -f "-Dcatalina.home=$CATALINA_HOME .*$START_CLASS"
```

I'm fine with this change though, +1

**Comment by cchesser** [comment]
> Does the 'No such file or directory' problem impact the tests at all? It looks like its just a warning and we are still able to stop/start the service fine. Either way, feel free to fix the vm so a home directory exists for the service user.

No, it will not fail the tests (see test evidence). Though, it should be corrected in the tests, as this warning shouldn't be occurring, based on the expectations of the provider (as it will attempt to navigate to the directory based on the login session).

**Comment by cchesser** [comment]
> If we wanted to exclude the (unrealistic) possibility of still resolving two PIDs when nesting a service within a service, we could do something like this instead (take note of the space and looking for catalina.home):

To be clear, this is just from the naming choices the consumer may use, where names are being expanded (my_tomcat, my_tomcat_1, my_tomcat_2). Unfortunately, this is a realistic problem, as we are encountering this case with the naming (as we deploy multiple Tomcat instances per host with similar name prefixes).

**Comment by EdwardSkoviak** [comment]
I didn't mean to imply the my_tomcat, my_tomcat_1, my_tomcat_2 problem was unrealistic. The change I proposed above was based on the fact your proposed fix wouldn't work for a case where one service was deployed inside the directory of another, e.g.:

```
/opt/my_dir/my_tomcat/my_tomcat_2/...
```

the pgrep command would still return two PIDs for the parent my_tomcat service.

**Comment by cchesser** [comment]
Ah, gotcha. Yeah, I'm good with making that change to avoid this scenario.

**Comment by EdwardSkoviak** [comment]
Changes look good. +1

Since we don't create the home directory within the provider, should we consider this a bug? Would I be correct to assume if we chef-client'd on a fresh vm we wouldn't have a home directory for the service user?

**Comment by cchesser** [comment]
> Since we don't create the home directory within the provider, should we consider this a bug? Would I be correct to assume if we chef-client'd on a fresh vm we wouldn't have a home directory for the service user?

Yeah, I'm not sure on that. I would assume so in how we are using that provider, but I haven't seen this on any of the VMs we have used this cookbook (they have a home directory). I can further verify if that is the case. I'm not sure if we even need to be using the login shell, as we are only wanting to run the process as that user and have it honor the user limits.

**Comment by cchesser** [comment]
Do we just need another reviewer on this PR to move this forward? I can document my findings on another Issue (for the case if there is an existing issue with the home directory / login shell for the init.d script).

**Comment by bbaugher** [comment]
+1

**Comment by noslowerdna** [comment]
+1

**Comment by bbaugher** [comment]
Have enough +1s, merging

**Pull request merged**
