### PR TITLE
#16: Offer start_on_install attribute

### PR DESCRIPTION
**Pull request by cchesser**
This change relates to issue #16, where `:start` is conditionally included. This is to allow consumers to dictate if service start should be applied immediately on install. Generally, this can be delayed as service restart will be applied at the end of the chef-client run.

test-kitchen verify results are [here](https://gist.github.com/cchesser/26191db09a4864d2b0fc9512492a2ad2). Note, I didn't change the tests, as they already verify the service process is running at the end of convergence.

### CODE REVIEW

**Comment by bbaugher** [comment]
+1

**Comment by cchesser** [comment]
There is actually a bug with this, as I'm not actually referring the the array being used. Let me correct, and extend the tests to have multiple Tomcat installs, to make it obvious between installs if starts are occurring.

**Comment by bbaugher** [comment]
Looks good, +1

**Comment by cchesser** [comment]
Applied 8eb942a, and updated the gist to include updated tests. Here is the service start-up logs as well (via the Ubuntu instance):

```
12-Sep-2016 19:55:14.461 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8001"]
12-Sep-2016 19:55:14.496 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
12-Sep-2016 19:55:14.500 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8003"]
12-Sep-2016 19:55:14.502 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
12-Sep-2016 19:55:14.502 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 888 ms
12-Sep-2016 19:55:14.531 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
12-Sep-2016 19:55:14.532 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.21
12-Sep-2016 19:55:14.581 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /opt/my_dir/my_tomcat/webapps/my_webapp.war
12-Sep-2016 19:55:15.041 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /opt/my_dir/my_tomcat/webapps/my_webapp.war has finished in 459 ms
12-Sep-2016 19:55:15.047 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8001"]
12-Sep-2016 19:55:15.057 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8003"]
12-Sep-2016 19:55:15.058 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 555 m
```

```
12-Sep-2016 19:55:21.926 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8011"]
12-Sep-2016 19:55:21.955 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
12-Sep-2016 19:55:21.963 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8013"]
12-Sep-2016 19:55:21.966 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
12-Sep-2016 19:55:21.966 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 878 ms
12-Sep-2016 19:55:21.999 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
12-Sep-2016 19:55:22.000 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.21
12-Sep-2016 19:55:22.051 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive /opt/my_dir/my_tomcat_2/webapps/my_webapp.war
12-Sep-2016 19:55:23.183 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive /opt/my_dir/my_tomcat_2/webapps/my_webapp.war has finished in 1,132 ms
12-Sep-2016 19:55:23.188 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8011"]
12-Sep-2016 19:55:23.198 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8013"]
12-Sep-2016 19:55:23.204 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 1238 ms
```

I would like to further verify this in our setup, so you can wait to finally merge after I post back a verification on another project (which caused me to evaluate this change). This is to avoid essentially two service starts in a single chef-client run.

**Comment by mkwhitacre** [comment]
+1

**Comment by cchesser** [comment]
Verified the changes, essentially by ensuring the service log did not contain multiple start events:

```
INFO: Server startup in ...
```

In this flow, the `restart` is processed after the service is enabled, vs. processing the `start` and then later the `restart` based on the delayed action.

Before:

```
    * service[tomcat_foo] action start[2016-09-12T16:47:29-05:00] INFO: Processing service[tomcat_foo] action start (/tmp/kitchen/cache/cookbooks/cerner_tomcat/providers/default.rb line 224)
[2016-09-12T16:48:56-05:00] INFO: service[tomcat_foo] started

      - start service service[tomcat_foo]
[2016-09-12T16:48:57-05:00] INFO: template[/opt/tomcat/foo/bin/setenv.sh] sending restart action to service[tomcat_foo] (delayed)
    * service[tomcat_foo] action restart[2016-09-12T16:48:57-05:00] INFO: Processing service[tomcat_foo] action restart (/tmp/kitchen/cache/cookbooks/cerner_tomcat/providers/default.rb line 224)
[2016-09-12T16:49:41-05:00] INFO: service[tomcat_foo] restarted

      - restart service service[tomcat_foo]
```

After:

```
    * service[tomcat_foo] action enable[2016-09-12T16:40:44-05:00] INFO: Processing service[tomcat_foo] action enable (/tmp/kitchen/cache/cookbooks/cerner_tomcat/providers/default.rb line 236)
[2016-09-12T16:40:44-05:00] INFO: service[tomcat_foo] enabled

      - enable service service[tomcat_foo]
[2016-09-12T16:40:44-05:00] INFO: template[/opt/tomcat/foo/bin/setenv.sh] sending restart action to service[tomcat_foo] (delayed)
    * service[tomcat_foo] action restart[2016-09-12T16:40:44-05:00] INFO: Processing service[tomcat_foo] action restart (/tmp/kitchen/cache/cookbooks/cerner_tomcat/providers/default.rb line 236)
[2016-09-12T16:42:12-05:00] INFO: service[tomcat_foo] restarted

      - restart service service[tomcat_foo]
```

**Comment by noslowerdna** [comment]
+1

**Comment by mkwhitacre** [comment]
Got enough +1s so ready to merge.  @cchesser one paperwork nit, can you add your name to: https://github.com/cerner/cerner_tomcat/blob/master/CONTRIBUTORS.txt

and make part of the PR.  Then we'll merge this in.

**Comment by cchesser** [comment]
@mkwhitacre, applied 24324ab to include my name on the `CONTRIBUTORS.txt` file.

**Comment by bbaugher** [comment]
Looks good, merging

**Pull request merged**
